/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/dictation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dictation Admin */
        get: operations["list_dictation_admin_api_v1_admin_dictation_get"];
        put?: never;
        /** Commit Dictation */
        post: operations["commit_dictation_api_v1_admin_dictation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dictation/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Dictation Paste */
        post: operations["parse_dictation_paste_api_v1_admin_dictation_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dictation/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dictation Sections Admin */
        get: operations["list_dictation_sections_admin_api_v1_admin_dictation_sections_get"];
        put?: never;
        /** Create Dictation Section */
        post: operations["create_dictation_section_api_v1_admin_dictation_sections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dictation/sections/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Dictation Section */
        delete: operations["delete_dictation_section_api_v1_admin_dictation_sections__section_id__delete"];
        options?: never;
        head?: never;
        /** Update Dictation Section */
        patch: operations["update_dictation_section_api_v1_admin_dictation_sections__section_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/dictation/sections/{section_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Dictation Section */
        post: operations["publish_dictation_section_api_v1_admin_dictation_sections__section_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dictation/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dictation Stories Admin */
        get: operations["list_dictation_stories_admin_api_v1_admin_dictation_stories_get"];
        put?: never;
        /** Create Dictation Story */
        post: operations["create_dictation_story_api_v1_admin_dictation_stories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dictation/stories/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Dictation Story */
        delete: operations["delete_dictation_story_api_v1_admin_dictation_stories__story_id__delete"];
        options?: never;
        head?: never;
        /** Update Dictation Story */
        patch: operations["update_dictation_story_api_v1_admin_dictation_stories__story_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/dictation/stories/{story_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Dictation Story */
        post: operations["publish_dictation_story_api_v1_admin_dictation_stories__story_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dictation/stories/{story_id}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Story Items */
        post: operations["reorder_story_items_api_v1_admin_dictation_stories__story_id__reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dictation/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dictation Topics Admin */
        get: operations["list_dictation_topics_admin_api_v1_admin_dictation_topics_get"];
        put?: never;
        /** Create Dictation Topic */
        post: operations["create_dictation_topic_api_v1_admin_dictation_topics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dictation/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Dictation Topic */
        delete: operations["delete_dictation_topic_api_v1_admin_dictation_topics__topic_id__delete"];
        options?: never;
        head?: never;
        /** Update Dictation Topic */
        patch: operations["update_dictation_topic_api_v1_admin_dictation_topics__topic_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/dictation/topics/{topic_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Dictation Topic */
        post: operations["publish_dictation_topic_api_v1_admin_dictation_topics__topic_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dictation/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Dictation Item */
        delete: operations["delete_dictation_item_api_v1_admin_dictation__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Dictation */
        patch: operations["update_dictation_api_v1_admin_dictation__item_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/dictation/{item_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Dictation */
        post: operations["publish_dictation_api_v1_admin_dictation__item_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["list_topics_api_v1_admin_topics_get"];
        put?: never;
        /** Create Topic */
        post: operations["create_topic_api_v1_admin_topics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vocabulary Admin */
        get: operations["list_vocabulary_admin_api_v1_admin_vocabulary_get"];
        put?: never;
        /** Commit Vocabulary */
        post: operations["commit_vocabulary_api_v1_admin_vocabulary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/vocabulary/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Vocabulary Paste
         * @description Parse a paste and report every problem. Writes nothing.
         */
        post: operations["parse_vocabulary_paste_api_v1_admin_vocabulary_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/vocabulary/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Vocabulary */
        patch: operations["update_vocabulary_api_v1_admin_vocabulary__entry_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/vocabulary/{entry_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Vocabulary */
        post: operations["publish_vocabulary_api_v1_admin_vocabulary__entry_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dictation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Dictation
         * @description Danh sách phẳng các câu đã xuất bản.
         *
         *     `standalone=true` lọc lấy những câu chưa thuộc story nào. Có tham số này vì
         *     cây topic→section→story ra đời sau: nếu luồng duyệt chỉ đi theo cây, mọi câu
         *     có từ trước sẽ biến mất khỏi tầm mắt học viên mà không có gì báo. Mặc định
         *     giữ nguyên hành vi cũ để không phá những chỗ đang gọi.
         */
        get: operations["list_dictation_api_v1_dictation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dictation-sections/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dictation Section */
        get: operations["get_dictation_section_api_v1_dictation_sections__section_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dictation-stories/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dictation Story */
        get: operations["get_dictation_story_api_v1_dictation_stories__story_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dictation-topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dictation Topics */
        get: operations["list_dictation_topics_api_v1_dictation_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dictation-topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dictation Topic */
        get: operations["get_dictation_topic_api_v1_dictation_topics__topic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dictation/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dictation */
        get: operations["get_dictation_api_v1_dictation__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dictation/{item_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Dictation */
        post: operations["submit_dictation_api_v1_dictation__item_id__attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["list_topics_api_v1_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vocabulary */
        get: operations["list_vocabulary_api_v1_vocabulary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vocabulary Progress
         * @description Trạng thái thuộc/chưa thuộc của học viên trên tập từ đang xem.
         *
         *     Lọc theo cùng tiêu chí `published` + topic như `GET /vocabulary`, nếu không
         *     mẫu số sẽ đếm cả những từ mà danh sách không hề hiện ra, và "đã thuộc 12/40"
         *     sẽ không bao giờ chạm tới 40.
         */
        get: operations["vocabulary_progress_api_v1_vocabulary_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary-review/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Session
         * @description Cards due now, then new ones up to the daily cap.
         *
         *     Due before new on purpose: reviewing what is about to be forgotten is worth
         *     more than meeting something for the first time, and if the session is cut
         *     short it should be the new words that wait.
         *
         *     `include_new=False` phục vụ những chế độ đòi học viên TỰ VIẾT RA từ. Bắt gõ
         *     lại một từ chưa từng thấy thì không có câu trả lời nào đúng được: lối thoát
         *     duy nhất là đoán bừa rồi ăn điểm 0. Với người mới thì cả 20/20 thẻ đều rơi
         *     vào cảnh đó — tôi phát hiện khi tự đóng vai học viên mới, không phải khi
         *     đọc code.
         */
        get: operations["review_session_api_v1_vocabulary_review_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vocabulary */
        get: operations["get_vocabulary_api_v1_vocabulary__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary/{entry_id}/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Recall
         * @description Gõ lại từ: máy chấm, rồi điểm SM-2 được suy ra từ kết quả.
         *
         *     Đây là điểm khác biệt duy nhất so với `/review`, và là lý do endpoint này
         *     tồn tại: thẻ lật hỏi "bạn có nhớ không" rồi ghi thẳng câu trả lời, nên
         *     người học có thể lật thẻ, nghĩ "à đúng rồi tôi biết mà", bấm Dễ và không
         *     học được gì. Ở đây phải viết ra được trước đã.
         */
        post: operations["submit_recall_api_v1_vocabulary__entry_id__recall_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary/{entry_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Review */
        post: operations["submit_review_api_v1_vocabulary__entry_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: the process is up. Deliberately checks no dependencies —
         *     a failing database should not get the container killed and restarted.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: can this instance actually serve traffic?
         *
         *     Returns 503 when Postgres is unreachable so a load balancer stops routing
         *     here. Redis is a soft dependency (see the startup path in app.main), so an
         *     outage there degrades rather than removes the instance.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AudioClip */
        AudioClip: {
            /** Accent */
            accent: string;
            /** Duration Ms */
            duration_ms: number;
            /** Url */
            url: string;
        };
        /** AudioSlotState */
        AudioSlotState: {
            /** Accent */
            accent: string;
            /** Kind */
            kind: string;
            /** State */
            state: string;
        };
        /** CommitResult */
        CommitResult: {
            /** Created */
            created: number;
            /** Problems */
            problems: string[];
            /** Skipped */
            skipped: number;
        };
        /** DictationAdmin */
        DictationAdmin: {
            /** Audio State */
            audio_state: string;
            /** Difficulty */
            difficulty: number;
            /** Id */
            id: string;
            /** Position */
            position?: number | null;
            /** Publishable */
            publishable: boolean;
            /** Status */
            status: string;
            /** Story Id */
            story_id?: string | null;
            /** Transcript */
            transcript: string;
        };
        /** DictationCommit */
        DictationCommit: {
            /**
             * Difficulty
             * @default 3
             */
            difficulty: number;
            /** Rows */
            rows: components["schemas"]["DictationRow"][];
            /** Story Id */
            story_id?: string | null;
            /** Topic Id */
            topic_id?: string | null;
        };
        /** DictationDetail */
        DictationDetail: {
            /** Audio Url */
            audio_url: string;
            /** Difficulty */
            difficulty: number;
            /** Duration Ms */
            duration_ms: number;
            /** Id */
            id: string;
            /** Topic Id */
            topic_id: string | null;
            /** Transcript */
            transcript: string;
            /** Word Count */
            word_count: number;
        };
        /** DictationParseResponse */
        DictationParseResponse: {
            /** Error Count */
            error_count: number;
            /** Ok Count */
            ok_count: number;
            /** Rows */
            rows: components["schemas"]["DictationRow"][];
        };
        /** DictationResult */
        DictationResult: {
            /** Accuracy */
            accuracy: string;
            /** Attempt Id */
            attempt_id: string;
            /** Diff */
            diff: components["schemas"]["WordDiff"][];
            /** Expected */
            expected: number;
            /** Is Complete */
            is_complete: boolean;
            /** Matched */
            matched: number;
            /** Transcript */
            transcript: string;
        };
        /** DictationRow */
        DictationRow: {
            /** Line */
            line: number;
            /**
             * Problems
             * @default []
             */
            problems: string[];
            /** Transcript */
            transcript: string;
        };
        /** DictationSectionAdmin */
        DictationSectionAdmin: {
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: number;
            /** Status */
            status: string;
            /** Story Count */
            story_count: number;
            /** Topic Id */
            topic_id: string;
            /** Topic Name */
            topic_name: string;
        };
        /** DictationSectionCreate */
        DictationSectionCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Topic Id */
            topic_id: string;
        };
        /** DictationSectionDetail */
        DictationSectionDetail: {
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Stories */
            stories: components["schemas"]["DictationStorySummary"][];
            /** Story Count */
            story_count: number;
            /** Topic Id */
            topic_id: string;
            /** Topic Name */
            topic_name: string;
        };
        /** DictationSectionPublic */
        DictationSectionPublic: {
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Story Count */
            story_count: number;
        };
        /** DictationSectionUpdate */
        DictationSectionUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /** Position */
            position?: number | null;
            /** Status */
            status?: string | null;
            /** Topic Id */
            topic_id?: string | null;
        };
        /** DictationStoryAdmin */
        DictationStoryAdmin: {
            /** Description */
            description: string | null;
            /** Difficulty */
            difficulty: number;
            /** Id */
            id: string;
            /** Item Count */
            item_count: number;
            /** Position */
            position: number;
            /** Publishable */
            publishable: boolean;
            /** Published Item Count */
            published_item_count: number;
            /** Section Id */
            section_id: string;
            /** Section Name */
            section_name: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Topic Name */
            topic_name: string;
        };
        /** DictationStoryCreate */
        DictationStoryCreate: {
            /** Description */
            description?: string | null;
            /**
             * Difficulty
             * @default 3
             */
            difficulty: number;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Section Id */
            section_id: string;
            /** Title */
            title: string;
        };
        /** DictationStoryDetail */
        DictationStoryDetail: {
            /** Description */
            description: string | null;
            /** Difficulty */
            difficulty: number;
            /** Id */
            id: string;
            /** Items */
            items: components["schemas"]["StoryItem"][];
            progress: components["schemas"]["StoryProgress"];
            /** Section Id */
            section_id: string;
            /** Section Name */
            section_name: string;
            /** Title */
            title: string;
            /** Topic Id */
            topic_id: string;
            /** Topic Name */
            topic_name: string;
        };
        /** DictationStorySummary */
        DictationStorySummary: {
            /** Description */
            description: string | null;
            /** Difficulty */
            difficulty: number;
            /** Id */
            id: string;
            progress: components["schemas"]["StoryProgress"];
            /** Title */
            title: string;
        };
        /** DictationStoryUpdate */
        DictationStoryUpdate: {
            /** Description */
            description?: string | null;
            /** Difficulty */
            difficulty?: number | null;
            /** Position */
            position?: number | null;
            /** Section Id */
            section_id?: string | null;
            /** Status */
            status?: string | null;
            /** Title */
            title?: string | null;
        };
        /** DictationSubmit */
        DictationSubmit: {
            /** Submitted Text */
            submitted_text: string;
        };
        /** DictationSummary */
        DictationSummary: {
            /** Difficulty */
            difficulty: number;
            /** Id */
            id: string;
            /** Topic Id */
            topic_id: string | null;
            /** Word Count */
            word_count: number;
        };
        /** DictationTopicAdmin */
        DictationTopicAdmin: {
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: number;
            /** Section Count */
            section_count: number;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
        };
        /** DictationTopicCreate */
        DictationTopicCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Slug */
            slug: string;
        };
        /** DictationTopicDetail */
        DictationTopicDetail: {
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Section Count */
            section_count: number;
            /** Sections */
            sections: components["schemas"]["DictationSectionPublic"][];
            /** Slug */
            slug: string;
        };
        /** DictationTopicPublic */
        DictationTopicPublic: {
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Section Count */
            section_count: number;
            /** Slug */
            slug: string;
        };
        /** DictationTopicUpdate */
        DictationTopicUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /** Position */
            position?: number | null;
            /** Slug */
            slug?: string | null;
            /** Status */
            status?: string | null;
        };
        /** DictationUpdate */
        DictationUpdate: {
            /** Difficulty */
            difficulty?: number | null;
            /** Status */
            status?: string | null;
            /** Story Id */
            story_id?: string | null;
            /** Topic Id */
            topic_id?: string | null;
            /** Transcript */
            transcript?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ParseRequest */
        ParseRequest: {
            /** Raw Text */
            raw_text: string;
        };
        /**
         * RecallResult
         * @description Kết quả chấm + lượt ôn đã ghi.
         *
         *     Kế thừa `ReviewResult` vì một lần gõ lại CHÍNH LÀ một lượt ôn: nó chạy qua
         *     đúng SM-2 đó và ghi đúng `vocabulary_review_log` đó. Khác biệt duy nhất là
         *     điểm do máy suy ra thay vì do người học tự bấm.
         */
        RecallResult: {
            /** Due At */
            due_at: string;
            /** Ease Factor */
            ease_factor: string;
            /** Entry Id */
            entry_id: string;
            /** Expected */
            expected: string;
            /** Grade */
            grade: number;
            /** Interval Days */
            interval_days: number;
            /** Lapses */
            lapses: number;
            /** Repetitions */
            repetitions: number;
            /** Typed */
            typed: string;
            /** Verdict */
            verdict: string;
        };
        /**
         * RecallSubmit
         * @description Một lần gõ lại từ.
         */
        RecallSubmit: {
            /**
             * Easy
             * @default false
             */
            easy: boolean;
            /**
             * Give Up
             * @default false
             */
            give_up: boolean;
            /**
             * Typed
             * @description Nguyên văn học viên gõ, không chuẩn hoá trước
             */
            typed: string;
        };
        /**
         * ReviewCard
         * @description A card in a review session.
         *
         *     `is_new` drives the daily new-card cap: without knowing which cards are new,
         *     the session cannot enforce a limit, and an uncapped queue of new words builds
         *     a review debt the learner meets a fortnight later.
         */
        ReviewCard: {
            /** Cefr Level */
            cefr_level: string | null;
            /** Difficulty */
            difficulty: number;
            /** Example */
            example: string | null;
            /** Example Audio */
            example_audio: components["schemas"]["AudioClip"][];
            /** Example Vi */
            example_vi: string | null;
            /** Headword */
            headword: string;
            /** Headword Audio */
            headword_audio: components["schemas"]["AudioClip"][];
            /** Id */
            id: string;
            /** Is New */
            is_new: boolean;
            /** Meaning En */
            meaning_en: string;
            /** Meaning Vi */
            meaning_vi: string;
            /** Part Of Speech */
            part_of_speech: string;
            /** Phonetic */
            phonetic: string | null;
        };
        /** ReviewResult */
        ReviewResult: {
            /** Due At */
            due_at: string;
            /** Ease Factor */
            ease_factor: string;
            /** Entry Id */
            entry_id: string;
            /** Grade */
            grade: number;
            /** Interval Days */
            interval_days: number;
            /** Lapses */
            lapses: number;
            /** Repetitions */
            repetitions: number;
        };
        /** ReviewSession */
        ReviewSession: {
            /** Cards */
            cards: components["schemas"]["ReviewCard"][];
            /** Due Count */
            due_count: number;
            /** New Count */
            new_count: number;
        };
        /** ReviewSubmit */
        ReviewSubmit: {
            /**
             * Grade
             * @description One of [0, 3, 4, 5]
             */
            grade: number;
        };
        /**
         * StoryItem
         * @description Một câu trong story, kèm việc học viên đã làm đúng nó hay chưa.
         */
        StoryItem: {
            /** Audio Url */
            audio_url: string;
            /** Completed */
            completed: boolean;
            /** Duration Ms */
            duration_ms: number;
            /** Id */
            id: string;
            /** Position */
            position: number;
            /** Transcript */
            transcript: string;
            /** Word Count */
            word_count: number;
        };
        /**
         * StoryProgress
         * @description Tiến độ của một học viên trên một story: đã làm đúng bao nhiêu câu.
         *
         *     Suy ra từ `dictation_attempt` chứ không đọc từ bảng tiến độ nào: một bảng ghi
         *     song song sẽ lệch khỏi lịch sử làm bài mà không có gì phát hiện.
         *
         *     Không còn điểm trung bình. Dictation đo được đúng một chuyện một cách đáng
         *     tin — nghe ra hay chưa — và một con số như "89%" không nói cho người học biết
         *     nên đi tiếp hay nghe lại. "3/6 câu đã xong" thì nói được.
         */
        StoryProgress: {
            /** Completed Items */
            completed_items: number;
            /** Total Items */
            total_items: number;
        };
        /** StoryReorder */
        StoryReorder: {
            /** Item Ids */
            item_ids: string[];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TopicAdmin */
        TopicAdmin: {
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: number;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
        };
        /** TopicCreate */
        TopicCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Slug */
            slug: string;
        };
        /** TopicPublic */
        TopicPublic: {
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: number;
            /** Slug */
            slug: string;
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserPublic */
        UserPublic: {
            /** Created At */
            created_at: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: string;
            /** Role */
            role: string;
        };
        /** UserRegister */
        UserRegister: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VocabularyAdmin */
        VocabularyAdmin: {
            /** Audio */
            audio: components["schemas"]["AudioSlotState"][];
            /** Headword */
            headword: string;
            /** Id */
            id: string;
            /** Meaning Vi */
            meaning_vi: string;
            /** Part Of Speech */
            part_of_speech: string;
            /** Publishable */
            publishable: boolean;
            /** Status */
            status: string;
        };
        /**
         * VocabularyCommit
         * @description Rows to write, after review.
         *
         *     The client sends back the (possibly edited) parse result rather than the raw
         *     paste, so what gets written is exactly what was on screen.
         */
        VocabularyCommit: {
            /**
             * Difficulty
             * @default 3
             */
            difficulty: number;
            /** Rows */
            rows: components["schemas"]["VocabularyRow"][];
            /** Topic Id */
            topic_id?: string | null;
        };
        /** VocabularyDetail */
        VocabularyDetail: {
            /** Cefr Level */
            cefr_level: string | null;
            /** Difficulty */
            difficulty: number;
            /** Example */
            example: string | null;
            /** Example Audio */
            example_audio: components["schemas"]["AudioClip"][];
            /** Example Vi */
            example_vi: string | null;
            /** Headword */
            headword: string;
            /** Headword Audio */
            headword_audio: components["schemas"]["AudioClip"][];
            /** Id */
            id: string;
            /** Meaning En */
            meaning_en: string;
            /** Meaning Vi */
            meaning_vi: string;
            /** Part Of Speech */
            part_of_speech: string;
            /** Phonetic */
            phonetic: string | null;
        };
        /**
         * VocabularyMastery
         * @description Trạng thái của một học viên trên MỘT từ.
         */
        VocabularyMastery: {
            /** Entry Id */
            entry_id: string;
            /** Is Due */
            is_due: boolean;
            /** Mastery */
            mastery: string;
        };
        /** VocabularyParseResponse */
        VocabularyParseResponse: {
            /** Error Count */
            error_count: number;
            /** Ok Count */
            ok_count: number;
            /** Rows */
            rows: components["schemas"]["VocabularyRow"][];
        };
        /**
         * VocabularyProgress
         * @description Tiến độ từ vựng của học viên, theo chủ đề hoặc trên toàn bộ.
         *
         *     Suy ra từ `vocabulary_review_state` chứ không đọc bảng tiến độ nào — cùng lý
         *     do đã ghi ở [`StoryProgress`]: một bảng ghi song song sẽ lệch khỏi lịch sử ôn
         *     tập mà không có gì phát hiện ra.
         *
         *     Đây là endpoint RIÊNG, có auth, chứ không phải thêm cột vào `GET /vocabulary`
         *     vốn là endpoint công khai. Nhét trạng thái người dùng vào đó thì với khách
         *     chưa đăng nhập, mọi từ sẽ mang giá trị `new` — một lời nói dối, chứ không
         *     phải "chưa có dữ liệu".
         */
        VocabularyProgress: {
            /** Due */
            due: number;
            /** Entries */
            entries: components["schemas"]["VocabularyMastery"][];
            /** Learning */
            learning: number;
            /** Mastered */
            mastered: number;
            /** New */
            new: number;
            /** Total */
            total: number;
        };
        /** VocabularyRow */
        VocabularyRow: {
            /** Example */
            example?: string | null;
            /** Example Vi */
            example_vi?: string | null;
            /** Headword */
            headword: string;
            /** Line */
            line: number;
            /** Meaning En */
            meaning_en: string;
            /** Meaning Vi */
            meaning_vi: string;
            /** Part Of Speech */
            part_of_speech: string;
            /** Phonetic */
            phonetic?: string | null;
            /**
             * Problems
             * @default []
             */
            problems: string[];
        };
        /** VocabularySummary */
        VocabularySummary: {
            /** Headword */
            headword: string;
            /** Id */
            id: string;
            /** Meaning Vi */
            meaning_vi: string;
            /** Part Of Speech */
            part_of_speech: string;
            /** Phonetic */
            phonetic: string | null;
        };
        /** VocabularyUpdate */
        VocabularyUpdate: {
            /** Difficulty */
            difficulty?: number | null;
            /** Example */
            example?: string | null;
            /** Example Vi */
            example_vi?: string | null;
            /** Headword */
            headword?: string | null;
            /** Meaning En */
            meaning_en?: string | null;
            /** Meaning Vi */
            meaning_vi?: string | null;
            /** Phonetic */
            phonetic?: string | null;
        };
        /** WordDiff */
        WordDiff: {
            /** Op */
            op: string;
            /** Word */
            word: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_dictation_admin_api_v1_admin_dictation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationAdmin"][];
                };
            };
        };
    };
    commit_dictation_api_v1_admin_dictation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictationCommit"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_dictation_paste_api_v1_admin_dictation_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dictation_sections_admin_api_v1_admin_dictation_sections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationSectionAdmin"][];
                };
            };
        };
    };
    create_dictation_section_api_v1_admin_dictation_sections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictationSectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationSectionAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dictation_section_api_v1_admin_dictation_sections__section_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dictation_section_api_v1_admin_dictation_sections__section_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictationSectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationSectionAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_dictation_section_api_v1_admin_dictation_sections__section_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationSectionAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dictation_stories_admin_api_v1_admin_dictation_stories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationStoryAdmin"][];
                };
            };
        };
    };
    create_dictation_story_api_v1_admin_dictation_stories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictationStoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationStoryAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dictation_story_api_v1_admin_dictation_stories__story_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dictation_story_api_v1_admin_dictation_stories__story_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictationStoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationStoryAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_dictation_story_api_v1_admin_dictation_stories__story_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationStoryAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_story_items_api_v1_admin_dictation_stories__story_id__reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryReorder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationAdmin"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dictation_topics_admin_api_v1_admin_dictation_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationTopicAdmin"][];
                };
            };
        };
    };
    create_dictation_topic_api_v1_admin_dictation_topics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictationTopicCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationTopicAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dictation_topic_api_v1_admin_dictation_topics__topic_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dictation_topic_api_v1_admin_dictation_topics__topic_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictationTopicUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationTopicAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_dictation_topic_api_v1_admin_dictation_topics__topic_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationTopicAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dictation_item_api_v1_admin_dictation__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dictation_api_v1_admin_dictation__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_dictation_api_v1_admin_dictation__item_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_api_v1_admin_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicAdmin"][];
                };
            };
        };
    };
    create_topic_api_v1_admin_topics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vocabulary_admin_api_v1_admin_vocabulary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyAdmin"][];
                };
            };
        };
    };
    commit_vocabulary_api_v1_admin_vocabulary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabularyCommit"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_vocabulary_paste_api_v1_admin_vocabulary_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vocabulary_api_v1_admin_vocabulary__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabularyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_vocabulary_api_v1_admin_vocabulary__entry_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dictation_api_v1_dictation_get: {
        parameters: {
            query?: {
                /** @description topic slug */
                topic?: string | null;
                /** @description only sentences that belong to no story */
                standalone?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dictation_section_api_v1_dictation_sections__section_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationSectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dictation_story_api_v1_dictation_stories__story_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationStoryDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dictation_topics_api_v1_dictation_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationTopicPublic"][];
                };
            };
        };
    };
    get_dictation_topic_api_v1_dictation_topics__topic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationTopicDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dictation_api_v1_dictation__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_dictation_api_v1_dictation__item_id__attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictationSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_api_v1_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicPublic"][];
                };
            };
        };
    };
    list_vocabulary_api_v1_vocabulary_get: {
        parameters: {
            query?: {
                /** @description topic slug */
                topic?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vocabulary_progress_api_v1_vocabulary_progress_get: {
        parameters: {
            query?: {
                /** @description topic slug */
                topic?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyProgress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_session_api_v1_vocabulary_review_session_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description False = chỉ những từ học viên đã gặp, không kèm từ mới */
                include_new?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vocabulary_api_v1_vocabulary__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_recall_api_v1_vocabulary__entry_id__recall_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecallSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecallResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_review_api_v1_vocabulary__entry_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
