"""Domain schema for Learning Hub and TOEIC Practice.

Implements planning/ADR-001-DATA-MODEL.md Part B. Thirteen tables in one
revision because they only make sense together: a question without its options
and its set is not a question.

Two shapes here look odd until you check the exam (ADR-001 A2): `question.set_id`
is nullable because only parts 3, 4, 6 and 7 group questions under a shared
stimulus, and `question.prompt_text` is nullable because part 2 prints nothing
at all.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "003_domain_schema"
down_revision: Union[str, None] = "002_audio_assets"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_test',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('full', 'mini')", name='ck_practice_test_kind'),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_practice_test_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_practice_test_status'), 'practice_test', ['status'], unique=False)
    op.create_table('topic',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_topic_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_topic_status'), 'topic', ['status'], unique=False)
    op.create_table('vocabulary_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('headword', sa.String(length=128), nullable=False),
    sa.Column('part_of_speech', sa.String(length=16), nullable=False),
    sa.Column('phonetic', sa.String(length=64), nullable=True),
    sa.Column('meaning_en', sa.Text(), nullable=False),
    sa.Column('meaning_vi', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('example_vi', sa.Text(), nullable=True),
    sa.Column('cefr_level', sa.String(length=4), nullable=True),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cefr_level IS NULL OR cefr_level IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')", name='ck_vocabulary_entry_cefr_level'),
    sa.CheckConstraint("part_of_speech IN ('noun', 'verb', 'adjective', 'adverb', 'preposition', 'phrase')", name='ck_vocabulary_entry_part_of_speech'),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_vocabulary_entry_status'),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='ck_vocabulary_entry_difficulty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('headword', 'part_of_speech', name='uq_vocabulary_entry_headword_pos')
    )
    op.create_index(op.f('ix_vocabulary_entry_headword'), 'vocabulary_entry', ['headword'], unique=False)
    op.create_index(op.f('ix_vocabulary_entry_status'), 'vocabulary_entry', ['status'], unique=False)
    op.create_table('attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=True),
    sa.Column('part', sa.SmallInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('listening_raw', sa.SmallInteger(), nullable=True),
    sa.Column('reading_raw', sa.SmallInteger(), nullable=True),
    sa.Column('listening_scaled', sa.SmallInteger(), nullable=True),
    sa.Column('reading_scaled', sa.SmallInteger(), nullable=True),
    sa.Column('total_scaled', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("(mode = 'full_test' AND test_id IS NOT NULL AND part IS NULL) OR (mode = 'part_practice' AND part IS NOT NULL AND test_id IS NULL)", name='ck_attempt_mode_fields'),
    sa.CheckConstraint("mode IN ('full_test', 'part_practice')", name='ck_attempt_mode'),
    sa.CheckConstraint('part IS NULL OR part BETWEEN 1 AND 7', name='ck_attempt_part'),
    sa.ForeignKeyConstraint(['test_id'], ['practice_test.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempt_user_started', 'attempt', ['user_id', 'started_at'], unique=False)
    op.create_table('dictation_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audio_asset_id', sa.Uuid(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_dictation_item_status'),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='ck_dictation_item_difficulty'),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_asset.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictation_item_status'), 'dictation_item', ['status'], unique=False)
    op.create_table('question_set',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('part', sa.SmallInteger(), nullable=False),
    sa.Column('audio_asset_id', sa.Uuid(), nullable=True),
    sa.Column('passage', sa.Text(), nullable=True),
    sa.Column('passage_2', sa.Text(), nullable=True),
    sa.Column('passage_3', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_question_set_status'),
    sa.CheckConstraint('part BETWEEN 1 AND 7', name='ck_question_set_part'),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_asset.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_set_part'), 'question_set', ['part'], unique=False)
    op.create_index(op.f('ix_question_set_status'), 'question_set', ['status'], unique=False)
    op.create_table('vocabulary_audio',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('accent', sa.String(length=8), nullable=False),
    sa.Column('audio_asset_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("accent IN ('en-US', 'en-GB', 'en-AU', 'en-CA')", name='ck_vocabulary_audio_accent'),
    sa.CheckConstraint("kind IN ('headword', 'example')", name='ck_vocabulary_audio_kind'),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_asset.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['vocabulary_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'kind', 'accent')
    )
    op.create_table('vocabulary_review_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade BETWEEN 0 AND 5', name='ck_vocabulary_review_log_grade'),
    sa.ForeignKeyConstraint(['entry_id'], ['vocabulary_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocabulary_review_log_user_entry', 'vocabulary_review_log', ['user_id', 'entry_id'], unique=False)
    op.create_table('vocabulary_review_state',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('ease_factor', sa.Numeric(precision=4, scale=2), server_default='2.50', nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ease_factor >= 1.30', name='ck_vocabulary_review_state_ease_factor'),
    sa.CheckConstraint('interval_days >= 0', name='ck_vocabulary_review_state_interval'),
    sa.ForeignKeyConstraint(['entry_id'], ['vocabulary_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'entry_id')
    )
    op.create_index('ix_vocabulary_review_state_due', 'vocabulary_review_state', ['user_id', 'due_at'], unique=False)
    op.create_table('vocabulary_topic',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['vocabulary_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'topic_id')
    )
    op.create_table('dictation_attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_text', sa.Text(), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('word_diff', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accuracy BETWEEN 0 AND 100', name='ck_dictation_attempt_accuracy'),
    sa.ForeignKeyConstraint(['item_id'], ['dictation_item.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictation_attempt_user_id'), 'dictation_attempt', ['user_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('part', sa.SmallInteger(), nullable=False),
    sa.Column('set_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('audio_asset_id', sa.Uuid(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('skill_tag', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('original', 'generated', 'licensed')", name='ck_question_source'),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_question_status'),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='ck_question_difficulty'),
    sa.CheckConstraint('part BETWEEN 1 AND 7', name='ck_question_part'),
    sa.CheckConstraint('part NOT IN (3, 4, 6, 7) OR set_id IS NOT NULL', name='ck_question_set_required'),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_asset.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['set_id'], ['question_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_part_status', 'question', ['part', 'status'], unique=False)
    op.create_index(op.f('ix_question_set_id'), 'question', ['set_id'], unique=False)
    op.create_index(op.f('ix_question_skill_tag'), 'question', ['skill_tag'], unique=False)
    op.create_index(op.f('ix_question_status'), 'question', ['status'], unique=False)
    op.create_table('practice_test_question',
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_id'], ['practice_test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id', 'question_id'),
    sa.UniqueConstraint('test_id', 'position', name='uq_practice_test_question_position')
    )
    op.create_table('question_option',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=1), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.CheckConstraint("label IN ('A', 'B', 'C', 'D')", name='ck_question_option_label'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'label', name='uq_question_option_label')
    )
    op.create_index(op.f('ix_question_option_question_id'), 'question_option', ['question_id'], unique=False)
    op.create_index('uq_question_option_single_correct', 'question_option', ['question_id'], unique=True, postgresql_where=sa.text('is_correct'), sqlite_where=sa.text('is_correct'))
    op.create_table('attempt_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('selected_option_id', sa.Uuid(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent_ms', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_option.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'position', name='uq_attempt_item_position'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_item_question')
    )
    op.create_index(op.f('ix_attempt_item_attempt_id'), 'attempt_item', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_item_question_id'), 'attempt_item', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_item_question_id'), table_name='attempt_item')
    op.drop_index(op.f('ix_attempt_item_attempt_id'), table_name='attempt_item')
    op.drop_table('attempt_item')
    op.drop_index('uq_question_option_single_correct', table_name='question_option', postgresql_where=sa.text('is_correct'), sqlite_where=sa.text('is_correct'))
    op.drop_index(op.f('ix_question_option_question_id'), table_name='question_option')
    op.drop_table('question_option')
    op.drop_table('practice_test_question')
    op.drop_index(op.f('ix_question_status'), table_name='question')
    op.drop_index(op.f('ix_question_skill_tag'), table_name='question')
    op.drop_index(op.f('ix_question_set_id'), table_name='question')
    op.drop_index('ix_question_part_status', table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_dictation_attempt_user_id'), table_name='dictation_attempt')
    op.drop_table('dictation_attempt')
    op.drop_table('vocabulary_topic')
    op.drop_index('ix_vocabulary_review_state_due', table_name='vocabulary_review_state')
    op.drop_table('vocabulary_review_state')
    op.drop_index('ix_vocabulary_review_log_user_entry', table_name='vocabulary_review_log')
    op.drop_table('vocabulary_review_log')
    op.drop_table('vocabulary_audio')
    op.drop_index(op.f('ix_question_set_status'), table_name='question_set')
    op.drop_index(op.f('ix_question_set_part'), table_name='question_set')
    op.drop_table('question_set')
    op.drop_index(op.f('ix_dictation_item_status'), table_name='dictation_item')
    op.drop_table('dictation_item')
    op.drop_index('ix_attempt_user_started', table_name='attempt')
    op.drop_table('attempt')
    op.drop_index(op.f('ix_vocabulary_entry_status'), table_name='vocabulary_entry')
    op.drop_index(op.f('ix_vocabulary_entry_headword'), table_name='vocabulary_entry')
    op.drop_table('vocabulary_entry')
    op.drop_index(op.f('ix_topic_status'), table_name='topic')
    op.drop_table('topic')
    op.drop_index(op.f('ix_practice_test_status'), table_name='practice_test')
    op.drop_table('practice_test')
    # ### end Alembic commands ###
