"""Images for Part 1, and the raw-to-scaled score conversion.

Closes the two gaps ADR-001 named but did not solve (§A6.1, §A6.2). See
ADR-004-IMAGES.md for why images get their own table rather than joining
audio_asset, and why licence and attribution are NOT NULL.

`question.image_url` becomes `question.image_asset_id`. Destructive on paper,
free in practice: no row has ever been written to `question`.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "004_images_and_scoring"
down_revision: Union[str, None] = "003_domain_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=False),
    sa.Column('attribution', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('transform_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('sourced', 'generated', 'uploaded')", name='ck_image_asset_source'),
    sa.CheckConstraint('width > 0 AND height > 0', name='ck_image_asset_dimensions'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_image_asset_source_hash'), 'image_asset', ['source_hash'], unique=True)
    op.create_table('score_scale',
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('score_conversion',
    sa.Column('scale_slug', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('raw_correct', sa.SmallInteger(), nullable=False),
    sa.Column('scaled_score', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("section IN ('listening', 'reading')", name='ck_score_conversion_section'),
    sa.CheckConstraint('raw_correct BETWEEN 0 AND 100', name='ck_score_conversion_raw'),
    sa.CheckConstraint('scaled_score BETWEEN 5 AND 495', name='ck_score_conversion_scaled'),
    sa.ForeignKeyConstraint(['scale_slug'], ['score_scale.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scale_slug', 'section', 'raw_correct')
    )
    op.add_column(
        'practice_test',
        sa.Column('score_scale_slug', sa.String(length=32), nullable=False, server_default='default'),
    )
    op.create_foreign_key(
        'fk_practice_test_score_scale', 'practice_test', 'score_scale',
        ['score_scale_slug'], ['slug'], ondelete='RESTRICT',
    )
    op.add_column('question', sa.Column('image_asset_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_question_image_asset', 'question', 'image_asset',
        ['image_asset_id'], ['id'], ondelete='RESTRICT',
    )
    op.drop_column('question', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_constraint('fk_question_image_asset', 'question', type_='foreignkey')
    op.drop_column('question', 'image_asset_id')
    op.drop_constraint('fk_practice_test_score_scale', 'practice_test', type_='foreignkey')
    op.drop_column('practice_test', 'score_scale_slug')
    op.drop_table('score_conversion')
    op.drop_table('score_scale')
    op.drop_index(op.f('ix_image_asset_source_hash'), table_name='image_asset')
    op.drop_table('image_asset')
    # ### end Alembic commands ###
