"""Roles and the content audit trail.

`users.role` gates the admin surface; `created_by` / `published_by` /
`published_at` answer "who approved this" when a wrong answer reaches a learner.
Both are cheap now and impossible to backfill later — every row written before
they existed is permanently untraceable.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "005_roles_and_audit"
down_revision: Union[str, None] = "004_images_and_scoring"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictation_item', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('dictation_item', sa.Column('published_by', sa.Uuid(), nullable=True))
    op.add_column('dictation_item', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'fk_dictation_item_created_by', 'dictation_item', 'users',
        ['created_by'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_dictation_item_published_by', 'dictation_item', 'users',
        ['published_by'], ['id'], ondelete='SET NULL',
    )
    op.add_column('practice_test', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('practice_test', sa.Column('published_by', sa.Uuid(), nullable=True))
    op.add_column('practice_test', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'fk_practice_test_created_by', 'practice_test', 'users',
        ['created_by'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_practice_test_published_by', 'practice_test', 'users',
        ['published_by'], ['id'], ondelete='SET NULL',
    )
    op.add_column('question', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('question', sa.Column('published_by', sa.Uuid(), nullable=True))
    op.add_column('question', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'fk_question_created_by', 'question', 'users',
        ['created_by'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_question_published_by', 'question', 'users',
        ['published_by'], ['id'], ondelete='SET NULL',
    )
    op.add_column('question_set', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('question_set', sa.Column('published_by', sa.Uuid(), nullable=True))
    op.add_column('question_set', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'fk_question_set_published_by', 'question_set', 'users',
        ['published_by'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_question_set_created_by', 'question_set', 'users',
        ['created_by'], ['id'], ondelete='SET NULL',
    )
    op.add_column('topic', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('topic', sa.Column('published_by', sa.Uuid(), nullable=True))
    op.add_column('topic', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'fk_topic_published_by', 'topic', 'users',
        ['published_by'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_topic_created_by', 'topic', 'users',
        ['created_by'], ['id'], ondelete='SET NULL',
    )
    op.add_column('users', sa.Column('role', sa.String(length=16), server_default='learner', nullable=False))
    op.create_check_constraint('ck_users_role', 'users', "role IN ('learner', 'editor', 'admin')")
    op.add_column('vocabulary_entry', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('vocabulary_entry', sa.Column('published_by', sa.Uuid(), nullable=True))
    op.add_column('vocabulary_entry', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'fk_vocabulary_entry_published_by', 'vocabulary_entry', 'users',
        ['published_by'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_vocabulary_entry_created_by', 'vocabulary_entry', 'users',
        ['created_by'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vocabulary_entry_created_by', 'vocabulary_entry', type_='foreignkey')
    op.drop_constraint('fk_vocabulary_entry_published_by', 'vocabulary_entry', type_='foreignkey')
    op.drop_column('vocabulary_entry', 'published_at')
    op.drop_column('vocabulary_entry', 'published_by')
    op.drop_column('vocabulary_entry', 'created_by')
    op.drop_constraint('ck_users_role', 'users', type_='check')
    op.drop_column('users', 'role')
    op.drop_constraint('fk_topic_created_by', 'topic', type_='foreignkey')
    op.drop_constraint('fk_topic_published_by', 'topic', type_='foreignkey')
    op.drop_column('topic', 'published_at')
    op.drop_column('topic', 'published_by')
    op.drop_column('topic', 'created_by')
    op.drop_constraint('fk_question_set_created_by', 'question_set', type_='foreignkey')
    op.drop_constraint('fk_question_set_published_by', 'question_set', type_='foreignkey')
    op.drop_column('question_set', 'published_at')
    op.drop_column('question_set', 'published_by')
    op.drop_column('question_set', 'created_by')
    op.drop_constraint('fk_question_published_by', 'question', type_='foreignkey')
    op.drop_constraint('fk_question_created_by', 'question', type_='foreignkey')
    op.drop_column('question', 'published_at')
    op.drop_column('question', 'published_by')
    op.drop_column('question', 'created_by')
    op.drop_constraint('fk_practice_test_published_by', 'practice_test', type_='foreignkey')
    op.drop_constraint('fk_practice_test_created_by', 'practice_test', type_='foreignkey')
    op.drop_column('practice_test', 'published_at')
    op.drop_column('practice_test', 'published_by')
    op.drop_column('practice_test', 'created_by')
    op.drop_constraint('fk_dictation_item_published_by', 'dictation_item', type_='foreignkey')
    op.drop_constraint('fk_dictation_item_created_by', 'dictation_item', type_='foreignkey')
    op.drop_column('dictation_item', 'published_at')
    op.drop_column('dictation_item', 'published_by')
    op.drop_column('dictation_item', 'created_by')
    # ### end Alembic commands ###
