"""Let a dictation item exist before its audio does.

The editor writes a transcript; the offline worker synthesises it afterwards,
because the API cannot import the TTS pipeline (PHASE2-AUDIO A4.1). So a draft
legitimately has no audio yet.

The CHECK is what keeps that intermediate state away from learners. It is
expressible here because the link is one column — the vocabulary equivalent
("has all four accents") spans rows in another table and only the publish
endpoint can enforce it.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "006_dictation_audio_optional"
down_revision: Union[str, None] = "005_roles_and_audit"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dictation_item', 'audio_asset_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_check_constraint('ck_dictation_item_published_has_audio', 'dictation_item', "status <> 'published' OR audio_asset_id IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_dictation_item_published_has_audio', 'dictation_item', type_='check')
    op.alter_column('dictation_item', 'audio_asset_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
