"""dictation completion flag

Revision ID: 008_dictation_completion_flag
Revises: 007_dictation_hierarchy
Create Date: 2026-08-09 22:23:47.866531
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "008_dictation_completion_flag"
down_revision: Union[str, None] = "007_dictation_hierarchy"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Các lượt làm đã có nhận `false`. Đó là câu trả lời đúng nhất có thể mà
    # không đọc lại `submitted_text` của từng hàng: cột này chỉ đánh dấu hoàn
    # thành, và không đánh dấu nhầm thì an toàn hơn đánh dấu bừa. Học viên chỉ
    # cần làm đúng thêm một lần là nó tự đúng.
    op.add_column(
        "dictation_attempt",
        sa.Column("is_complete", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dictation_attempt", "is_complete")
    # ### end Alembic commands ###
