"""ai_interaction

Revision ID: 015_ai_interaction
Revises: 014_audio_script
Create Date: 2026-08-12 02:45:32.156894
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '015_ai_interaction'
down_revision: Union[str, None] = '014_audio_script'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('feature', sa.String(length=48), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ok', 'error', 'refused')", name='ck_ai_interaction_status'),
    sa.CheckConstraint('prompt_tokens >= 0 AND completion_tokens >= 0 AND cached_tokens >= 0', name='ck_ai_interaction_tokens_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interaction_feature'), 'ai_interaction', ['feature'], unique=False)
    op.create_index(op.f('ix_ai_interaction_request_id'), 'ai_interaction', ['request_id'], unique=False)
    op.create_index('ix_ai_interaction_user_created', 'ai_interaction', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_interaction_user_created', table_name='ai_interaction')
    op.drop_index(op.f('ix_ai_interaction_request_id'), table_name='ai_interaction')
    op.drop_index(op.f('ix_ai_interaction_feature'), table_name='ai_interaction')
    op.drop_table('ai_interaction')
    # ### end Alembic commands ###
