"""ai_interaction observability

Revision ID: 016_ai_observability
Revises: 015_ai_interaction
Create Date: 2026-08-12 10:14:33.297213
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '016_ai_observability'
down_revision: Union[str, None] = '015_ai_interaction'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `server_default` trên ba cột NOT NULL: thêm một cột không-null vào bảng
    # đã có hàng thì Postgres phải điền gì đó cho các hàng cũ, và không có mặc
    # định thì ALTER hỏng. Bảng này đang rỗng nên chỗ này chưa nổ ở máy dev —
    # nó sẽ nổ ở môi trường đã chạy thật, tức là chỗ tệ nhất để phát hiện.
    op.add_column('ai_interaction', sa.Column('prompt_version', sa.String(length=64), nullable=True))
    op.add_column('ai_interaction', sa.Column('tool_calls', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('ai_interaction', sa.Column('retries', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('ai_interaction', sa.Column('cache_hit', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_interaction', 'cache_hit')
    op.drop_column('ai_interaction', 'retries')
    op.drop_column('ai_interaction', 'tool_calls')
    op.drop_column('ai_interaction', 'prompt_version')
    # ### end Alembic commands ###
