"""skill tag review

Revision ID: 017_skill_tag_review
Revises: 016_ai_observability
Create Date: 2026-08-12 11:07:51.726453
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '017_skill_tag_review'
down_revision: Union[str, None] = '016_ai_observability'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('skill_tag_proposed', sa.String(length=32), nullable=True))
    op.add_column('question', sa.Column('skill_tag_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'skill_tag_reviewed_at')
    op.drop_column('question', 'skill_tag_proposed')
    # ### end Alembic commands ###
