"""skill tag reviewer

Revision ID: 018_skill_tag_reviewer
Revises: 017_skill_tag_review
Create Date: 2026-08-12 12:05:39.745777
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '018_skill_tag_reviewer'
down_revision: Union[str, None] = '017_skill_tag_review'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('skill_tag_reviewed_by', sa.Uuid(), nullable=True))
    # Đặt TÊN cho ràng buộc. Alembic tự sinh `None`, mà một khoá ngoại không tên
    # thì `downgrade` không drop được — nó nổ ngay ở dòng đầu với "it has no
    # name". Không ai chạy downgrade cho tới lúc thật sự cần, nên đây là loại
    # hỏng chỉ lộ ra ở đúng lúc tệ nhất.
    op.create_foreign_key(
        "fk_question_skill_tag_reviewed_by_users",
        "question",
        "users",
        ["skill_tag_reviewed_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_question_skill_tag_reviewed_by_users", "question", type_="foreignkey")
    op.drop_column('question', 'skill_tag_reviewed_by')
    # ### end Alembic commands ###
