"""question label taxonomy

Revision ID: 019_question_labels
Revises: 018_skill_tag_reviewer
Create Date: 2026-08-12 13:00:26.585395
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '019_question_labels'
down_revision: Union[str, None] = '018_skill_tag_reviewer'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_set_label',
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.Column('facet', sa.String(length=24), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('proposed_code', sa.String(length=48), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['set_id'], ['question_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_id', 'facet')
    )
    op.create_index(op.f('ix_question_set_label_code'), 'question_set_label', ['code'], unique=False)
    op.create_table('question_label',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('facet', sa.String(length=24), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('proposed_code', sa.String(length=48), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('question_id', 'facet')
    )
    op.create_index(op.f('ix_question_label_code'), 'question_label', ['code'], unique=False)
    op.drop_index(op.f('ix_question_skill_tag'), table_name='question')
    op.drop_constraint(op.f('fk_question_skill_tag_reviewed_by_users'), 'question', type_='foreignkey')
    op.drop_column('question', 'skill_tag_reviewed_at')
    op.drop_column('question', 'skill_tag_proposed')
    op.drop_column('question', 'skill_tag')
    op.drop_column('question', 'skill_tag_reviewed_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('skill_tag_reviewed_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('skill_tag', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('skill_tag_proposed', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('skill_tag_reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_question_skill_tag_reviewed_by_users'), 'question', 'users', ['skill_tag_reviewed_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_question_skill_tag'), 'question', ['skill_tag'], unique=False)
    op.drop_index(op.f('ix_question_label_code'), table_name='question_label')
    op.drop_table('question_label')
    op.drop_index(op.f('ix_question_set_label_code'), table_name='question_set_label')
    op.drop_table('question_set_label')
    # ### end Alembic commands ###
