"""ai feature config

Revision ID: 020_ai_feature_config
Revises: 019_question_labels
Create Date: 2026-08-12 15:33:23.051710
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '020_ai_feature_config'
down_revision: Union[str, None] = '019_question_labels'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_feature_config',
    sa.Column('feature', sa.String(length=48), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('feature')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_feature_config')
    # ### end Alembic commands ###
