"""option translation

Revision ID: 023_option_translation
Revises: 022_coach_chat
Create Date: 2026-08-13 20:05:29.279177
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '023_option_translation'
down_revision: Union[str, None] = '022_coach_chat'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_option', sa.Column('content_vi', sa.Text(), nullable=True))
    op.add_column('question_option', sa.Column('spoken_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_option', 'spoken_text')
    op.drop_column('question_option', 'content_vi')
    # ### end Alembic commands ###
