import type { SceneDef } from "@/content/scenes/types";

export const warehouseScene: SceneDef = {
  id: "warehouse-01",
  title: "Trong nhà kho",
  description: "Kho hàng, bến dỡ hàng và đường ra — nơi logistics TOEIC sống.",
  topicSlug: "logistics",
  sky: "#e9edf0",
  environment: "warehouse-lot",
  badges: ["new"],
  objects: [
    {
      id: "obj-warehouse",
      shape: "warehouse",
      headword: "warehouse",
      partOfSpeech: "noun",
      position: [-4.5, 0, -5.5],
      focusDistance: 10.5,
      hotspotY: 4.1,
      ringRadius: 4.6,
    },
    {
      id: "obj-loading-bay",
      shape: "loading-bay",
      headword: "loading bay",
      partOfSpeech: "noun",
      position: [2.8, 0, -3.4],
      focusDistance: 5.5,
      hotspotY: 2.6,
      ringRadius: 1.7,
    },
    {
      id: "obj-depot",
      shape: "depot",
      headword: "depot",
      partOfSpeech: "noun",
      position: [7.6, 0, -5.8],
      focusDistance: 7,
      hotspotY: 3.1,
      ringRadius: 2.6,
    },
    {
      id: "obj-forklift",
      shape: "forklift",
      headword: "forklift",
      partOfSpeech: "noun",
      position: [-0.6, 0, -0.9],
      rotationY: -0.6,
      focusDistance: 4.4,
      hotspotY: 2.2,
      ringRadius: 1.5,
    },
    {
      id: "obj-pallet",
      shape: "pallet",
      headword: "pallet",
      partOfSpeech: "noun",
      position: [2.4, 0, 0.8],
      rotationY: 0.35,
      focusDistance: 2.8,
      hotspotY: 0.8,
      ringRadius: 1.0,
    },
    {
      id: "obj-consignment",
      shape: "consignment-crate",
      headword: "consignment",
      partOfSpeech: "noun",
      // Dịch ra sau-trái so với spec: ở góc nhìn đầu, nhãn của nó đè đúng giữa
      // nhãn `forklift` và ăn mất cú bấm (test "mọi hotspot đều bấm được").
      position: [-3.1, 0, 2.7],
      rotationY: 0.2,
      focusDistance: 3.4,
      hotspotY: 1.9,
      ringRadius: 1.1,
    },
    {
      id: "obj-courier",
      shape: "courier-van",
      headword: "courier",
      partOfSpeech: "noun",
      position: [5.2, 0, 4.2],
      patrol: { axis: "x", range: 4.5, speed: 0.9 },
      focusDistance: 5,
      hotspotY: 2.4,
      ringRadius: 1.9,
    },
    {
      id: "obj-clipboard",
      shape: "clipboard",
      headword: "tracking number",
      partOfSpeech: "noun",
      position: [6.4, 0, -1.4],
      /* 0.3 = hướng camera mặc định: phiếu kiểm kê quay mặt về nơi người học
         đứng, để ngược thì chỉ thấy tấm bảng nâu. */
      rotationY: 0.3,
      focusDistance: 2.8,
      hotspotY: 2.0,
      ringRadius: 0.9,
    },
  ],
};
